name: MFh
on: 
  push    
  #workflow_dispatch

env:
  SERVER_HOST: '85.28.47.165'
  SERVER_USER: root
  SERVER_PATH: /var/www/ws/backfromgithub


jobs:

  deployJobs:
    runs-on: ubuntu-latest
    steps:
    - name: part1
      uses: actions/checkout@v2
       # Setup key
    - name: part2
      run: set -eu

    - name: part3  
      run: mkdir "$HOME/.ssh"
    
    - name: part4
      run: echo "${{ secrets.PKEY }}" > "$HOME/.ssh/key"

    - name: part5
      run: chmod 600 "$HOME/.ssh/key"

      # Deploy
    - name: part6
      run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}

    - name: part7 - deploy new content from github
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ secrets.PKEY }}
        script: |
           rm -rf /var/www/ws/backfromgithub/.git/
           rm -rf /var/www/ws/backfromgithub/.github/
           rm  /var/www/ws/backfromgithub/.gitignore
           cp -r /var/www/ws/backfromgithub/* /var/www/ws/
           cd /var/www/ws/
           pm2 restart websocket --update-env 